version:
  "3"
services:
  application1:
    image : minseokey/chat_server
    depends_on:
      - redis
    container_name: application1
    restart: always
    ports:
     - "8081:8080"
    environment:
      REDIS_HOST: redis
      TZ: "Asia/Seoul"
      WEBSOCKET_PORT: 8081

  application2:
    image : minseokey/chat_server
    depends_on:
      - redis
    container_name: application2
    restart: always
    ports:
      - "8082:8080"
    environment:
      REDIS_HOST: redis
      TZ: "Asia/Seoul"
      WEBSOCKET_PORT: 8082

  application3:
    image : minseokey/chat_server
    depends_on:
      - redis
    container_name: application3
    restart: always
    ports:
      - "8083:8080"
    environment:
      REDIS_HOST: redis
      TZ: "Asia/Seoul"
      WEBSOCKET_PORT: 8083

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6378:6379"
    restart: always
    environment:
        TZ: "Asia/Seoul"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - application1
      - application2
      - application3
    restart: always
    environment:
        TZ: "Asia/Seoul"